# ~/.alacritty.toml
#   see: https://alacritty.org/config-alacritty.html

[env]
# force constant device pixel ratio to avoid massive font size when moving terminal
# across monitors with different pixel densities
WINIT_X11_SCALE_FACTOR = "1.0"

# [font]
# size = 11.0
# offset.x = 0    # for letter spacing (default: 0)
# offset.y = -1   # for line spacing (default: 0)
# # see: `fc-list : family style | grep -i 'sf mono'`
# [font.normal]
# family = "SF Mono"
# style = "Bold"
# [font.bold]
# family = "SF Mono"
# style = "Bold"
# [font.italic]
# family = "SF Mono"
# style = "Bold"
# [font.bold_italic]
# family = "SF Mono"
# style = "Bold"

[font]
size = 11.5
offset.x = 0    # for letter spacing (default: 0)
offset.y = -3   # for line spacing (default: 0)
# see: `fc-list : family style | grep -i 'jetbrains'`
[font.normal]
family = "JetBrains Mono"
style = "ExtraBold"
[font.bold]
family = "JetBrains Mono"
style = "ExtraBold"
[font.italic]
family = "JetBrains Mono"
style = "ExtraBold"
[font.bold_italic]
family = "JetBrains Mono"
style = "ExtraBold"

[colors]
draw_bold_text_with_bright_colors = true

# photons-mod
[colors.primary]
background = "#1A1A1A"
foreground = "#FCFCFC"
[colors.normal]
black      = "#393939"
red        = "#C72D41"
green      = "#85C600"
yellow     = "#FFA600"
blue       = "#3465A4"
magenta    = "#931645"
cyan       = "#0099BC"
white      = "#D9D2BD"
[colors.bright]
black      = "#404A4D"
red        = "#FF5D4A"
green      = "#B3FF1D"
yellow     = "#FEED6C"
blue       = "#3C91D2"
magenta    = "#BE4773"
cyan       = "#5CDEDE"
white      = "#85919B"
